### ISSUE TITLE
请问在哪里可以找到保存的打卡信息呢？

### ISSUE THREAD

**Issue by hadesmercy** [Rominwolf/daily-attendance-mirai#1]

**Comment by Rominwolf** [comment]
如果是配置文件的打卡信息，可以在 `<Mirai 根目录下>/config/ink.wsm.mirai.daily_attendance_v2.plugin/` 找到
如果是用户/群聊的打卡信息，可以在 `<Mirai 根目录下>/data/ink.wsm.mirai.daily_attendance_v2.plugin/` 找到
